global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'todo-app-real'
    static_configs:
      - targets: ['host.docker.internal:5001']  # VOTRE APP RÃ‰ELLE
    metrics_path: '/metrics'
    scrape_interval: 10s