global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # --- ADD THESE TWO JOBS ---
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # This job scrapes your backend application
  - job_name: 'todo-backend'
    static_configs:
      - targets: ['backend:5000'] # This should match your service name and port
    metrics_path: '/metrics'
    scrape_interval: 15s